routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\InternController;
use App\Http\Controllers\ControlController;
use App\Http\Controllers\ApplicationController;
 
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Aqui se colocan las rutas a trabajar en el sitio web */
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::resource('/intern', InternController::class);
Route::group(['middleware' => 'auth'],function(){
    Route::resource('/users', UserController::class);
    Route::resource('/manager', ManagerController::class);
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/intern/mostrar_evaluacion/{id}',[App\Http\Controllers\EvaluationController::class, 'ShowEvaluation']);
    Route::get('/intern/mostrar_evaluacion/create/{id}',[App\Http\Controllers\EvaluationController::class, 'CreateEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/store',[App\Http\Controllers\EvaluationController::class, 'StoreEvaluation']);
    Route::get('/intern/mostrar_evaluacion/{id}/edit/{id_segundo}',[App\Http\Controllers\EvaluationController::class, 'EditEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/update/{id_segundo}',[App\Http\Controllers\EvaluationController::class, 'UpdateEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/destroy',[App\Http\Controllers\EvaluationController::class, 'DestroyEvaluation']);
    Route::post('/control_register/{id}/update',[App\Http\Controllers\ControlController::class, 'UpdateControl']);
    Route::post('/control_register/{id}/destroy',[App\Http\Controllers\ControlController::class, 'DestroyControl']);
    Route::resource('/control_register', ControlController::class);
    Route::resource('/application_requests', ApplicationController::class); 
    Route::post('/intern/{id}/destroy', [App\Http\Controllers\InternController::class,'destroy']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
         'name',
         'role',
         'dni',
         'phone',
         'photo_profile',
         'email',
         'address',
         'password',
    ];


    protected $table="users";
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {   
        $users = User::all();
        return view('users.users',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create_user');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Aqui se validan los campos antes de guardarlos en la base de datos
        $rules = [
            'user_name' => 'required',
            'role' => 'required',
            'Password2' => 'required',
            'photo_profile' => 'required|image|mimes:jpg,jpeg,png,svg|max:1024'
        ];
        
        //Aqui se modifican los mensajes de validacion antes de guardarlos en la base de datos
        $messages = [
            'user_name.required' => 'Agrega el nombre del usuario.',
            'role.required' => 'Agrega el nombre del usuario',
            'Password2.required' =>'Confirme la contraseña.',
            'photo_profile.required' => 'Confirma que el tipo sea una imagen jpeg, jpg, png o el tamaño del archivo menor a 1MB.'
        ];
            
        $this->validate($request, $rules, $messages);

        $user = new User;
        $user->name = $request->user_name;
        $user->role = $request->role;
        $user->dni = $request->dni;
        $user->phone = $request->phone;
        $user->email = $request->email;
        $user->address = $request->address;
        if($request->Password1 == $request->Password2){
            $user->password = bcrypt($request->Password1);
        }

        if($imagen = $request->file('photo_profile')){
            $ruta = '/dist/img/';
            $imagenuser = $user->name.'.'.$imagen->getClientOriginalExtension();
            $imagen->move($ruta,$imagenuser);
            $user->photo_profile = $imagenuser;
        }else{
            $user->photo_profile = "default.png";
        }

        $user->save();

        return redirect()->route('users.index')
            ->with('success','El usuario ha sido creada exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit_user',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $user)
    {
        $rules = [
            'user_name' => 'required',
            'role' => 'required',
        ];
        
        $messages = [
            'user_name.required' => 'Agrega el nombre del usuario.',
            'role.required' => 'Agrega el nombre del usuario',
        ];
            
        $this->validate($request, $rules, $messages);

        $user = User::find($user);
        $user->name = $request->user_name;
        $user->role = $request->role;
        $user->dni = $request->dni;
        $user->phone = $request->phone;
        $user->email = $request->email;
        $user->address = $request->address;
        if(!empty($request->Password1)){
            if($request->Password1 == $request->Password2){
                $user->password = bcrypt($request->Password1);
            }
        }

        if($imagen = $request->file('photo_profile')){
            $ruta = '/dist/img/';
            $imagenuser = $user->name.'.'.$imagen->getClientOriginalExtension();
            $imagen->move($ruta,$imagenuser);
            $user->photo_profile = $imagenuser;
        }

        $user->save();

        return redirect()->route('users.index')
            ->with('success','El usuario ha sido creada exitosamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index')
        ->with('success','El usuario ha sido eliminado exitosamente.');
    }
}

resources/views/users/create_user.blade.php
@extends('layouts.main')

@section('title', 'Crear Usuario - Administración')

@section('section')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Crear Usuario
                    </h3>
                    <a type="button" class="btn btn-primary float-right" href="{{ route('users.index') }}"> Regresar</a>
                </div>
                <div class="card-body">
                    <form action="{{ route('users.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                        <div class="row">   
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Nombre completo</label>
                                    <input type="text" class="form-control" id="user_name" name="user_name">
                                    @error('user_name')
                                    <div class="alert alert-warning alert-dismissible mt-2">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                        <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                                        {{ $message }}
                                    </div>
                                    @enderror      
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>DNI</label>
                                    <input type="text" class="form-control" id="dni" name="dni">
                                </div>
                            </div>
                        </div>
                        <div class="row">   
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="exampleSelectBorder">Rol de Usuario</label>
                                    <select class="custom-select form-control-border" id="role" name="role">
                                        <option value="0">Administrador</option>
                                        <option value="1">Usuario</option>
                                    </select>
                                    @error('role')
                                    <div class="alert alert-warning alert-dismissible mt-2">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                        <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Tel&eacute;fono</label>
                                    <input type="text" class="form-control" id="phone" name="phone">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control" id="email" name="email">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Direcci&oacute;n</label>
                                    <input type="text" class="form-control" id="address" name="address">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                <label for="exampleInputPassword1">Contraseña</label>
                                <input type="password" class="form-control" id="Password1" name="Password1">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                <label for="exampleInputPassword1">Confirmar Contraseña</label>
                                <input type="password" class="form-control" id="Password2" name="Password2">
                                </div>
                            </div>    
                        </div>
                        <div class="row">
                            <div class="col-sm col-md-6 col-lg-4">
                                <img id="img-mostrar" class="img-fluid" style="max-height:300px;">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="exampleInputFile">Foto</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="photo_profile" name="photo_profile">
                                            <label class="custom-file-label" for="exampleInputFile">Escoger el archivo</label>
                                        </div>
                                        @error('photo_profile')
                                        <div class="alert alert-warning alert-dismissible mt-2">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                            <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                                            {{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button  type="submit" class="btn btn-success">Guardar</button>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
$(document).ready(function(e){
    $('#photo_profile').change(function(){
        let reader = new FileReader();
        reader.onload = (e) => {
            $('#img-mostrar').attr('src',e.target.result);
        }
        reader.readAsDataURL(this.files[0]);
    });
});
</script>

@endsection      

resources/views/users/edit_user.blade.php
@extends('layouts.main')

@section('title', 'Editar Usuario - Administración')

@section('section')
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">
            Editar Usuario
          </h3>
          <a type="button" class="btn btn-primary float-right" href="{{ route('users.index') }}"> Regresar</a>
        </div>
        <div class="card-body">
          <form action="{{ route('users.update',$user->id) }}" method="POST" enctype="multipart/form-data">
          @csrf
          @method('PUT')
            <div class="row">   
              <div class="col-6">
                <div class="form-group">
                  <label>Nombre completo</label>
                  <input type="text" class="form-control" id="user_name" name="user_name" value="{{ $user->name }}">
                  @error('user_name')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror      
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                  <label>DNI</label>
                  <input type="text" class="form-control" id="dni" name="dni" value="{{ $user->dni }}">
                </div>
              </div>
            </div>
            <div class="row">   
              <div class="col-6">
                <div class="form-group">
                  <label for="exampleSelectBorder">Rol de Usuario</label>
                  <select class="custom-select form-control-border" id="role" name="role">
                    <option <?php if (($user->role)== 0){ echo "selected"; } ?> value="0">Administrador</option>
                    <option <?php if (($user->role)== 1){ echo "selected"; } ?> value="1">Usuario</option>
                  </select>
                  @error('role')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                  <label>Tel&eacute;fono</label>
                  <input type="text" class="form-control" id="phone" name="phone" value="{{ $user->phone }}">
                </div>
              </div>
            </div>
            <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" class="form-control" id="email" name="email" value="{{ $user->email }}">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Direcci&oacute;n</label>
                                    <input type="text" class="form-control" id="address" name="address" value="{{ $user->address }}">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                <label for="exampleInputPassword1">Contraseña</label>
                                <input type="password" class="form-control" id="Password1" name="Password1">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                <label for="exampleInputPassword1">Confirmar Contraseña</label>
                                <input type="password" class="form-control" id="Password2" name="Password2">
                                </div>
                            </div>    
                        </div>
                        <div class="row">
                            <div class="col-sm col-md-6 col-lg-4">
                                <img id="img-mostrar" src="/dist/img/{{ $user->photo_profile }}" class="img-fluid" style="max-height:300px;">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="exampleInputFile">Foto</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="photo_profile" name="photo_profile">
                                            <label class="custom-file-label" for="exampleInputFile">Escoger el archivo</label>
                                        </div>
                                        @error('photo_profile')
                                        <div class="alert alert-warning alert-dismissible mt-2">
                                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                            <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                                            {{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
          <button  type="submit" class="btn btn-success">Guardar</button>
          </form>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
$(document).ready(function(e){
    $('#photo_profile').change(function(){
        let reader = new FileReader();
        reader.onload = (e) => {
            $('#img-mostrar').attr('src',e.target.result);
        }
        reader.readAsDataURL(this.files[0]);
    });
});
</script>
@endsection

resources/views/users/users.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Usuarios - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-check"></i> Alerta!</h5>
              <p>{{ $message }}</p>
            </div>
          @endif
          <div class="card-header">
            <h3 class="card-title">
                Administraci&oacute;n de Usuarios
            </h3>
            <a type="button" class="btn btn-success float-right" href="{{ route('users.create') }}"><i class="fas fa-plus"></i> Agregar</a>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>#</th>
                <th>Nombre Completo</th>
                <th>DNI</th>
                <th>Tel&eacute;fono</th>
                <th>Correo electr&oacute;nico</th>
                <th>Acciones</th>
              </tr>
              </thead>
              <tbody>
                @foreach ($users as $user)
                <tr>
                <td>1</td>
                <td>{{$user->name}}
                </td>
                <td>{{$user->dni}}
                </td>
                <td>{{$user->phone}}
                </td>
                <td>{{$user->email}}
                </td>
               
                <td><div class="btn-group">
                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" data-offset="-52" aria-expanded="true">
                      <i class="fas fa-bars"></i>
                    </button>
                    <div class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-52px, 31px, 0px);">
                      <form action="{{ route('users.destroy',$user->id) }}" method="Post">
                        <a href="{{ route('users.edit',$user->id) }}" class="dropdown-item"> <i class="fas fa-bars"></i> Editar</a>
                        @csrf
                        @method('DELETE')
                        <button  type="submit" class="dropdown-item"> <i class="fas fa-bars"></i> Eliminar</button> 
                      </form>
                    </div>
                  </div></td>
              </tr>
                @endforeach
                
              
              </tbody>
              <tfoot>
              <tr>
                <th>#</th>
                <th>Nombre Completo</th>
                <th>DNI</th>
                <th>Tel&eacute;fono</th>
                <th>Correo electr&oacute;nico</th>
                <th>Acciones</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
@endsection