routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\InternController;
use App\Http\Controllers\ControlController;
use App\Http\Controllers\ApplicationController;
 
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Aqui se colocan las rutas a trabajar en el sitio web */
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::resource('/intern', InternController::class);
Route::group(['middleware' => 'auth'],function(){
    Route::resource('/users', UserController::class);
    Route::resource('/manager', ManagerController::class);
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/intern/mostrar_evaluacion/{id}',[App\Http\Controllers\EvaluationController::class, 'ShowEvaluation']);
    Route::get('/intern/mostrar_evaluacion/create/{id}',[App\Http\Controllers\EvaluationController::class, 'CreateEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/store',[App\Http\Controllers\EvaluationController::class, 'StoreEvaluation']);
    Route::get('/intern/mostrar_evaluacion/{id}/edit/{id_segundo}',[App\Http\Controllers\EvaluationController::class, 'EditEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/update/{id_segundo}',[App\Http\Controllers\EvaluationController::class, 'UpdateEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/destroy',[App\Http\Controllers\EvaluationController::class, 'DestroyEvaluation']);
    Route::post('/control_register/{id}/update',[App\Http\Controllers\ControlController::class, 'UpdateControl']);
    Route::post('/control_register/{id}/destroy',[App\Http\Controllers\ControlController::class, 'DestroyControl']);
    Route::resource('/control_register', ControlController::class);
    Route::resource('/application_requests', ApplicationController::class); 
    Route::post('/intern/{id}/destroy', [App\Http\Controllers\InternController::class,'destroy']);
});

app/Models/Intern.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Intern extends Model
{
    use HasFactory;

    protected $table="intern";
}

app/Http/Controllers/InternController.php
<?php

namespace App\Http\Controllers;

use App\Models\Intern;
use App\Models\Manager;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use App\Mail\internMessage;
use App\Mail\internAccept;
use Illuminate\Support\Facades\Storage;
use File;

class InternController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $interns = Intern::all();

        return view('interns.interns',compact('interns'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $count_manager = Manager::all()->sum('vacancy');
        $managers = Manager::where("vacancy",">",0)->get();

        return view('interns.create_intern',compact('count_manager','managers'));
    }

    /** 
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $manager = Manager::find($request->manager_id);
        if($manager->vacancy!=0){
         //Aqui se validan los campos antes de guardarlos en la base de datos
         $rules = [
            'name' => 'required',
            'lastname' => 'required',
            'dni' => 'required|min:13|numeric|unique:intern',
            'email' => 'required|unique:intern',
            'career' => 'required',
            'institution_name' => 'required',
            'number_months_internship' => 'required|integer',
            'internship_application' => 'mimes:pdf',
            'curriculum_vitae' => 'mimes:pdf',
            'covid19_exam' => 'mimes:pdf'
        ];
        
            //Aqui se modifican los mensajes de validacion antes de guardarlos en la base de datos
            $messages = [
                'name.required' => 'Ingresa tu nombre',
                'lastname.required' => 'Ingresa tu apellido',
                'dni.required' =>'Ingresa tu DNI(número de identidad)',
                'dni.min' =>'El DNI ingresado debe contener 13 digitos, sin guiones(-) o algun otro caracter, ni letras',
                'dni.numeric' =>'El DNI ingresado debe contener solo digitos minimo (13), sin guiones(-) o algun otro caracter, ni letras',
                'dni.unique' =>'Este DNI ya esta ingresado en el sistema, porfavor verifique si el DNI ingresado es el correcto.',
                'email.required' => 'Ingresa tu correo electronico',
                'email.unique' =>'Este correo electronico ya esta ingresado en el sistema, porfavor verifique si el correo electronico ingresado es el correcto.',
                'career.required' => 'Ingresa tu carrera',
                'institution_name.required' => 'Ingresa el nombre de la institución',
                'number_months_internship.required' => 'Ingresa la cantidad de meses que durara la Práctica',
                'number_months_internship.integer' =>'Este campo ingresado solo debe contener digitos, sin guiones(-) o algun otro caracter, ni letras',
                'internship_application.mimes' => 'Debe adjuntar archivos solo que sean en <strong>PDF</strong>',
                'curriculum_vitae.mimes' => 'Debe adjuntar archivos solo que sean en <strong>PDF</strong>',
                'covid19_exam.mimes' => 'Debe adjuntar archivos solo que sean en <strong>PDF</strong>'
            ];
            
            $this->validate($request, $rules, $messages);

            $intern = new Intern;
            $intern->name = $request->name;
            $intern->lastname = $request->lastname;
            $intern->dni = $request->dni;
            $intern->phone = $request->phone;
            $intern->email = $request->email;
            $intern->place_residence = $request->place_residence;
            $intern->career = $request->career;
            $intern->status = '1';
            $intern->university = $request->university;
            $intern->institution_name = $request->institution_name;
            $intern->idmanager = $request->manager_id;
            $intern->internship_month = $request->internship_month;
            $intern->number_months_internship = $request->number_months_internship;

            if($request->hasFile('internship_application')){
                $archivo_internship_application=$request->file('internship_application');
                $archivo_internship_application->move(public_path().'/pdf/'.$intern->dni.'/',$archivo_internship_application->getClientOriginalName());
                $intern->internship_application = $archivo_internship_application->getClientOriginalName();
            }

            if($request->hasFile('curriculum_vitae')){
                $archivo_curriculum_vitae=$request->file('curriculum_vitae');
                $archivo_curriculum_vitae->move(public_path().'/pdf/'.$intern->dni.'/',$archivo_curriculum_vitae->getClientOriginalName());
                $intern->curriculum_vitae = $archivo_curriculum_vitae->getClientOriginalName();
            }

            if($request->hasFile('covid19_exam')){
                $archivo_covid19_exam=$request->file('covid19_exam');
                $archivo_covid19_exam->move(public_path().'/pdf/'.$intern->dni.'/',$archivo_covid19_exam->getClientOriginalName());
                $intern->covid19_exam = $archivo_covid19_exam->getClientOriginalName();
            }

            $intern->name = $request->name;
            $intern->save();

            
            $manager->vacancy = $manager->vacancy - 1;
            $manager->save();

            return redirect()->route('intern.create')
            ->with('success', $intern->name . ' '.$intern->lastname .' has sido registrado exitosamente. Se le notificara por medio de correo eléctronico si su solicitud ha sido aprobada o rechazada.');
        }else{
            return redirect()->route('intern.create')
            ->with('errores',' Lamentamos informar que en esta gerencia ya no se encuentran vacantes disponibles por favor vuelva a intentarlo nuevamente con una gerencia disponible.');
        }
        }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Intern  $intern
     * @return \Illuminate\Http\Response
     */
    public function show(Intern $intern)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Intern  $intern
     * @return \Illuminate\Http\Response
     */
    public function edit($intern)
    {
        $correo = new internAccept;
        $interncod = Intern::find($intern);
        $interncod->status = 2;
        $interncod->save();
        Mail::to($interncod->email)->send($correo);

        return redirect('/application_requests')
        ->with('success','El practicante ha sido aceptado exitosamente.');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Intern  $intern
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Intern $intern)
    {
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Intern  $intern
     * @return \Illuminate\Http\Response
     */
    public function destroy($intern)
    {
        $correo = new internMessage;
        $interncod = Intern::find($intern);
        $manager = Manager::find($interncod->idmanager);
        $manager->vacancy = $manager->vacancy + 1;
        $manager->save();
        $url = 'pdf/'.$interncod->dni;
        File::deleteDirectory(public_path($url));
        Mail::to($interncod->email)->send($correo);
        $interncod->delete();
        return redirect('/application_requests')
        ->with('success','El practicante ha sido rechazado exitosamente.');
    }
}

resources/views/interns/create_intern.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.register_intern')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Registrarse')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')

<div class="container-fluid">
    <div class="row">
      {{-- Aqui se hace una condicion donde si en las gerencias no hay ninguna vacante entonces tirara el mensaje de que no puede registrarse y si hay vacantes podra acceder al formulario --}}
      @if ($count_manager==0)
      <div class="col-12">
          <div class="row">   
            <div class="col-12">
              <h4><b>Lamentamos informar que no se encuentran vacantes en ningun área para poder aplicar en estos momentos.</b></h4>
              @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-check"></i> Alerta!</h5>
              <p>{{ $message }}</p>
            </div>
            @endif
            </div>
          </div> 
        @else
        <div class="col-12">
          <p class="login-box-msg text-left"><span class="text-danger">*</span>Registrese para poder aplicar a un area, los campos que contengan este asterisco <span class="text-danger">*</span> significan que son obligatorios de llenar.</p>
          <div class="card-header mb-3">
            <h4><b>Información Personal</b></h4>
            @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-check"></i> Alerta!</h5>
              <p>{{ $message }}</p>
            </div>
            @endif
            @if ($message = Session::get('errores'))
            <div class="alert alert-danger alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-check"></i> Alerta!</h5>
              <p>{{ $message }}</p>
            </div>
            @endif
          </div>
          <form action="{{ route('intern.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">   
              <div class="col-6">
                <div class="form-group">
                  <label>Nombre<span class="text-danger">*</span></label>
                  <input type="text" class="form-control" value="{{old('name')}}" id="name" name="name">
                  @error('name')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror      
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                  <label>Apellido<span class="text-danger">*</span></label>
                  <input type="text" class="form-control" value="{{old('lastname')}}" id="lastname" name="lastname">
                  @error('lastname')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror      
                </div>
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="form-group">
                  <label>DNI<span class="text-danger">*</span></label>
                  <input type="text" class="form-control" value="{{old('dni')}}" id="dni" name="dni" maxlength="13">
                  @error('dni')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror      
                </div>
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="form-group">
                  <label>Teléfono</label>
                  <input type="number" class="form-control" value="{{old('phone')}}" id="phone" name="phone">
                </div>
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="form-group">
                  <label>Correo electrónico<span class="text-danger">*</span></label>
                  <input type="email" class="form-control" value="{{old('email')}}"  id="email" name="email">
                  @error('email')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror      
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                    <label>¿Gerencia a la cual desea aplicar?</label>
                    <select class="form-control" id="manager_id" name="manager_id">
                      @foreach ($managers as $manager)
                       <option value="{{$manager->id}}">{{$manager->manager}}</option>
                      @endforeach
                    </select>    
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Lugar de residencia</label>
                  <input type="text" class="form-control" value="{{old('place_residence')}}" id="place_residence" name="place_residence"> 
                </div>
              </div>
              <div class="col-12 card-header mb-3">
                <h4><b>Información Académica</b></h4>
              </div>
              <div class="col-6">
                <div class="form-group">
                  <label>Carrera<span class="text-danger">*</span></label>
                  <input type="text" class="form-control" value="{{old('career')}}" id="career" name="career">
                  @error('career')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror      
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                    <label>¿Es Colegio o Universidad?</label>
                    <select class="form-control" value="{{old('university')}}" id="university" name="university">
                      <option>Colegio</option>
                      <option>Universidad</option>
                    </select>    
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                  <label>Nombre de la institución<span class="text-danger">*</span></label>
                  <input type="text" class="form-control" value="{{old('institution_name')}}" id="institution_name" name="institution_name">
                  @error('institution_name')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror      
                </div>
              </div>
              <div class="col-6">
                <div class="form-group">
                    <label>¿Mes en que hará la practica?</label>
                    <select class="form-control"  id="internship_month" name="internship_month">
                      <option value="1">Enero</option>
                      <option value="2">Febrero</option>
                      <option value="3">Marzo</option>
                      <option value="4">Abril</option>
                      <option value="5">Mayo</option>
                      <option value="6">Junio</option>
                      <option value="7">Julio</option>
                      <option value="8">Agosto</option>
                      <option value="9">Septiembre</option>
                      <option value="10">Octubre</option>
                      <option value="11">Noviembre</option>
                      <option value="12">Diciembre</option>
                    </select>    
                </div>
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="form-group">
                  <label>¿Cuantos meses durara la práctica profesional?<span class="text-danger">*</span></label>
                  <input type="number" class="form-control" value="{{old('number_months_internship')}}" id="number_months_internship" name="number_months_internship">
                  @error('number_months_internship')
                  <div class="alert alert-warning alert-dismissible mt-2">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                    {{ $message }}
                  </div>
                  @enderror      
                </div>
              </div>
              <div class="col-12 card-header mb-3">
                <h4><b>Documentos</b></h4>
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="form-group">
                  <label for="customFile">Solicitud de práctica</label>
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" id="internship_application" name="internship_application">
                    <label class="custom-file-label" for="customFile">Escoje el archivo</label>
                    @error('internship_application')
                    <div class="alert alert-warning alert-dismissible mt-2">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                      @php
                          echo html_entity_decode($message)
                      @endphp
                    </div>
                    @enderror 
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="form-group">
                  <label for="customFile">Hoja de Vida</label>
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" id="curriculum_vitae" name="curriculum_vitae">
                    <label class="custom-file-label" for="customFile">Escoje el archivo</label>
                    @error('curriculum_vitae')
                    <div class="alert alert-warning alert-dismissible mt-2">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                      @php
                          echo html_entity_decode($message)
                      @endphp
                    </div>
                    @enderror 
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-4">
                <div class="form-group">
                  <label for="customFile">Examen de Covid 19</label>
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" id="covid19_exam" name="covid19_exam">
                    <label class="custom-file-label" for="customFile">Escoje el archivo</label>
                    @error('covid19_exam')
                    <div class="alert alert-warning alert-dismissible mt-2">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                      @php
                          echo html_entity_decode($message)
                      @endphp
                    </div>
                    @enderror 
                  </div>
                </div>
              </div>
             
            </div>
           <button  type="submit" class="btn btn-success">Enviar</button>
          </form>
  
  
      
          <!-- /.card -->
        </div> 
      @endif
    
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>

@endsection

resources/views/interns/evaluations.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Documentacion y Evaluacion - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
                Administraci&oacute;n para Documentacion y Evaluaci&oacute;n de Practicantes
            </h3>
            <a type="button" class="btn btn-success float-right" href="/intern/mostrar_evaluacion/create/{{$id_intern}}"><i class="fas fa-plus"></i> Agregar</a>
            <a type="button" class="btn btn-primary float-right" href="/intern"><i class="fas fa-arrow-left"></i> Regresar</a>
          
         </div>
         
          <!-- /.card-header -->
          {{-- Lista de Gerencias --}}
          <div class="card-body">
            @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-check"></i> Alerta!</h5>
              <p>{{ $message }}</p>
            </div>
            @endif
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>Documentos</th>
                <th>Estado</th>
                <th>Correcciones</th>
                <th>Nota</th>
                <th>Acciones</th>
              </tr>
              </thead>
              <tbody>
                @foreach ($evaluations as $evaluation)
                <tr>
                <td>{{$evaluation->description}}
                <a href="/pdf/evaluaciones/{{$evaluation->file}}" target="_blank"> Ver</a>
                </td>
                <td>
                  @if ($evaluation->status==1)
                    <button  class="btn btn-success">Aprobado</button>   
                  @else
                    <button  class="btn btn-danger">Reprobado</button>    
                  @endif
                </td>
                <td>
                  @if ($evaluation->correction=='Culminado')
                    <button  class="btn btn-success">Culminado</button>   
                  @else
                    <button  class="btn btn-primary">Pendiente</button>    
                  @endif
                </td>
                <td>
                  {{$evaluation->grade}}
                </td>
                <td><div class="btn-group">
                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" data-offset="-52" aria-expanded="true">
                      <i class="fas fa-bars"></i>
                    </button>
                    <div class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-52px, 31px, 0px);">
                        <form action="{{ url('/intern/mostrar_evaluacion/'.$evaluation->id.'/destroy') }}" method="Post">
                          @csrf
                          <a href="{{ url('/intern/mostrar_evaluacion/'.$id_intern.'/edit/'.$evaluation->id) }}" class="dropdown-item"> <i class="fas fa-bars"></i> Editar</a>
                      
                          <button  type="submit" class="dropdown-item"> <i class="fas fa-bars"></i> Eliminar</button> 
                        </form>
                       
                     </div>
                  </div>
                </td>
              </tr>
                @endforeach
               <tr>
                <td> - </td>
                <td> - </td>
                <td> - </td>
                <td><strong> Nota Promedio: {{$promgradeevaluation}}</strong></td>
                <td> - </td>
               </tr>
              </tbody>
              <tfoot>
              <tr>
                <th>Documentos</th>
                <th>Estado</th>
                <th>Correcciones</th>
                <th>Nota</th>
                <th>Acciones</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
@endsection

resources/views/interns/interns.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Evaluacion para Practicantes - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
                Administraci&oacute;n para Evaluaci&oacute;n de Practicantes
            </h3>
         </div>
          <!-- /.card-header -->
          {{-- Lista de Gerencias --}}
          <div class="card-body">
            @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-check"></i> Alerta!</h5>
              <p>{{ $message }}</p>
            </div>
            @endif
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>Nombre de Practicante</th>
                <th>Carrera</th>
                <th>Nombre de la Instituci&oacute;n</th>
                <th>Acciones</th>
              </tr>
              </thead>
              <tbody>
                @foreach ($interns as $intern)
                @if ($intern->status == 2)
                <tr>
                <td>{{$intern->name}} {{$intern->lastname}} 
                </td>
                <td>{{$intern->career}}
                </td>
                <td>{{$intern->institution_name}} 
                </td>
                <td><div class="btn-group">
                     <a href="/intern/mostrar_evaluacion/{{$intern->id}}" type="button" class="btn btn-primary"><i class="far fa-eye"></i> Evaluar</a>     
                  </div></td>
                </tr>
                @endif
                @endforeach
              </tbody>
              <tfoot>
              <tr>
                <th>Nombre de Practicante</th>
                <th>Carrera</th>
                <th>Nombre de la Instituci&oacute;n</th>
                <th>Acciones</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
@endsection