routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\InternController;
use App\Http\Controllers\ControlController;
use App\Http\Controllers\ApplicationController;
 
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Aqui se colocan las rutas a trabajar en el sitio web */
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::resource('/intern', InternController::class);
Route::group(['middleware' => 'auth'],function(){
    Route::resource('/users', UserController::class);
    Route::resource('/manager', ManagerController::class);
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/intern/mostrar_evaluacion/{id}',[App\Http\Controllers\EvaluationController::class, 'ShowEvaluation']);
    Route::get('/intern/mostrar_evaluacion/create/{id}',[App\Http\Controllers\EvaluationController::class, 'CreateEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/store',[App\Http\Controllers\EvaluationController::class, 'StoreEvaluation']);
    Route::get('/intern/mostrar_evaluacion/{id}/edit/{id_segundo}',[App\Http\Controllers\EvaluationController::class, 'EditEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/update/{id_segundo}',[App\Http\Controllers\EvaluationController::class, 'UpdateEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/destroy',[App\Http\Controllers\EvaluationController::class, 'DestroyEvaluation']);
    Route::post('/control_register/{id}/update',[App\Http\Controllers\ControlController::class, 'UpdateControl']);
    Route::post('/control_register/{id}/destroy',[App\Http\Controllers\ControlController::class, 'DestroyControl']);
    Route::resource('/control_register', ControlController::class);
    Route::resource('/application_requests', ApplicationController::class); 
    Route::post('/intern/{id}/destroy', [App\Http\Controllers\InternController::class,'destroy']);
});

resources/views/control_register/controls.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Control de Registro - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
                Administraci&oacute;n de Control de Registro
            </h3>
            <a type="button" class="btn btn-success float-right" href="{{ route('control_register.create') }}"><i class="fas fa-plus"></i> Agregar</a>
          </div>
         
          <!-- /.card-header -->
          {{-- Lista de Gerencias --}}
          <div class="card-body">
            @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-check"></i> Alerta!</h5>
              <p>{{ $message }}</p>
            </div>
            @endif
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>Practicante</th>
                <th>Gerencia</th>
                <th>Descripción</th>
                <th>Fecha Inicio</th>
                <th>Fecha Final</th>
                <th>Horario</th>
                <th>Horas de Practica</th>
                <th>Acciones</th>
              </tr>
              </thead>
              <tbody>
                @foreach ($controls as $control)
                <tr>
                  @foreach ($interns as $intern)
                      @if ($intern->id==$control->id_intern)
                      <td>{{$intern->name}} {{$intern->lastname}}
                      </td>
                      @endif
                  @endforeach
                  @foreach ($managers as $manager)
                  @if ($manager->id==$control->id_manager)
                  <td>{{$manager->manager}}
                  </td>
                  @endif
              @endforeach
                <td>{{$control->description}}
                </td>
                <td>{{$control->fecha_inicio}}
                </td>
                <td>{{$control->fecha_final}}
                </td>
                <td>{{$control->horario}}
                </td>
                <td>{{$control->horas_practica}}
                </td>
                <td><div class="btn-group">
                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" data-offset="-52" aria-expanded="true">
                      <i class="fas fa-bars"></i>
                    </button>
                    <div class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-52px, 31px, 0px);">
                      <form action="{{ url('/control_register/'.$control->id.'/destroy') }}" method="Post">
                        <a href="{{ route('control_register.edit',$control->id) }}" class="dropdown-item"> <i class="fas fa-bars"></i> Editar</a>
                        @csrf
                      
                        <button  type="submit" class="dropdown-item"> <i class="fas fa-bars"></i> Eliminar</button> 
                      </form>
                     </div>
                  </div></td>
              </tr>
                @endforeach
              </tbody>
              <tfoot>
              <tr>
                <th>Practicante</th>
                <th>Gerencia</th>
                <th>Descripción</th>
                <th>Fecha Inicio</th>
                <th>Fecha Final</th>
                <th>Horario</th>
                <th>Horas de Practica</th>
                <th>Acciones</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
@endsection

resources/views/control_register/create_control.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Crear Control de Registro - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
                Crear Control de Registro
            </h3>
            <a type="button" class="btn btn-primary float-right" href="{{ route('control_register.index') }}"> Regresar</a>
          </div>
        
          <div class="card-body">
           {{-- Formulario Para guardar la Gerencia --}}
           <form action="{{ route('control_register.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">   
              <div class="col-md-6">
                <div class="form-group">
                    <label>Nombre del Practicante</label>
                    <select class="form-control" id="id_intern" name="id_intern">
                      @foreach ($interns as $intern)
                          @if ($intern->status == 2)
                          <option value="{{$intern->id}}">{{$intern->name }} {{$intern->lastname}}</option>
                          @endif
                      @endforeach
                    </select>    
                </div>
              </div>
          <div class="col-6">
            <div class="form-group">
              <label>Descripción</label>
              <input type="text" class="form-control" id="description" name="description">
              @error('description')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <label>Fecha inicial</label>
                    <div class="input-group date" id="fecha_inicial" name="fecha_inicial" data-target-input="nearest">
                        <input type="text" class="form-control datetimepicker-input" id="fecha_inicial_control" name="fecha_inicial_control"  data-target="#fecha_inicial"/>
                        <div class="input-group-append" data-target="#fecha_inicial" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
              @error('fecha_inicial_control')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <label>Fecha Final</label>
                    <div class="input-group date" id="fecha_final" name="fecha_final" data-target-input="nearest">
                        <input type="text" class="form-control datetimepicker-input" id="fecha_final_control" name="fecha_final_control"  data-target="#fecha_final"/>
                        <div class="input-group-append" data-target="#fecha_final" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
              @error('fecha_final_control')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <label>Horario</label>
              <input type="text" class="form-control" id="horario" name="horario">
              @error('horario')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <label>Horas de Practica</label>
              <input type="text" class="form-control" id="horas_practica" name="horas_practica">
              @error('horas_practica')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>
        
          </div>
          <button  type="submit" class="btn btn-success">Guardar</button>
          </form>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>

@endsection

resources/views/control_register/edit_control.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Editar Control de Registro - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
               Editar Control de Registro
            </h3>
            <a type="button" class="btn btn-primary float-right" href="{{ route('control_register.index') }}"> Regresar</a>
          </div>
        
          <div class="card-body">
           {{-- Formulario Para guardar la Gerencia --}}
           <form action="{{ url("/control_register/$control->id/update") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">   
              <div class="col-md-6">
                <div class="form-group">
                    <label>Nombre del Practicante</label>
                    <select class="form-control" id="id_intern" name="id_intern">
                      @foreach ($interns as $intern)
                      @if ($intern->id==$control->id_intern)
                      <option value="{{$intern->id}}" selected>{{$intern->name }} {{$intern->lastname}}</option>
                      @else
                        @if ($intern->status == 2)
                      <option value="{{$intern->id}}">{{$intern->name }} {{$intern->lastname}}</option>
                        @endif
                      @endif
                      @endforeach
                    </select>    
                </div>
              </div>
          <div class="col-6">
            <div class="form-group">
              <label>Descripción</label>
              <input type="text" class="form-control" value="{{$control->description}}" id="description" name="description">
              @error('description')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <label>Fecha inicial</label>
                    <div class="input-group date" id="fecha_inicial"  name="fecha_inicial" data-target-input="nearest">
                        <input type="text" class="form-control datetimepicker-input" value="{{$control->fecha_inicio}}" id="fecha_inicial_control" name="fecha_inicial_control"  data-target="#fecha_inicial"/>
                        <div class="input-group-append" data-target="#fecha_inicial" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
              @error('fecha_inicial_control')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <label>Fecha Final</label>
                    <div class="input-group date" id="fecha_final"  name="fecha_final" data-target-input="nearest">
                        <input type="text" class="form-control datetimepicker-input" value="{{$control->fecha_final}}" id="fecha_final_control" name="fecha_final_control"  data-target="#fecha_final"/>
                        <div class="input-group-append" data-target="#fecha_final" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
              @error('fecha_final_control')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <label>Horario</label>
              <input type="text" class="form-control" id="horario" value="{{$control->horario}}" name="horario">
              @error('horario')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <label>Horas de Practica</label>
              <input type="text" class="form-control" id="horas_practica" value="{{$control->horas_practica}}" name="horas_practica">
              @error('horas_practica')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>
        
          </div>
          <button  type="submit" class="btn btn-success">Guardar</button>
          </form>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>

@endsection