routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ManagerController;
use App\Http\Controllers\InternController;
use App\Http\Controllers\ControlController;
use App\Http\Controllers\ApplicationController;
 
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Aqui se colocan las rutas a trabajar en el sitio web */
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();
Route::resource('/intern', InternController::class);
Route::group(['middleware' => 'auth'],function(){
    Route::resource('/users', UserController::class);
    Route::resource('/manager', ManagerController::class);
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/intern/mostrar_evaluacion/{id}',[App\Http\Controllers\EvaluationController::class, 'ShowEvaluation']);
    Route::get('/intern/mostrar_evaluacion/create/{id}',[App\Http\Controllers\EvaluationController::class, 'CreateEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/store',[App\Http\Controllers\EvaluationController::class, 'StoreEvaluation']);
    Route::get('/intern/mostrar_evaluacion/{id}/edit/{id_segundo}',[App\Http\Controllers\EvaluationController::class, 'EditEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/update/{id_segundo}',[App\Http\Controllers\EvaluationController::class, 'UpdateEvaluation']);
    Route::post('/intern/mostrar_evaluacion/{id}/destroy',[App\Http\Controllers\EvaluationController::class, 'DestroyEvaluation']);
    Route::post('/control_register/{id}/update',[App\Http\Controllers\ControlController::class, 'UpdateControl']);
    Route::post('/control_register/{id}/destroy',[App\Http\Controllers\ControlController::class, 'DestroyControl']);
    Route::resource('/control_register', ControlController::class);
    Route::resource('/application_requests', ApplicationController::class); 
    Route::post('/intern/{id}/destroy', [App\Http\Controllers\InternController::class,'destroy']);
});

app/Models/Manager.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Manager extends Model
{
    use HasFactory;

    protected $table="management";
}

app/Http/Controllers/ManagerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Manager;
use Illuminate\Http\Request;

class ManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $managers = Manager::all();
        
        return view('manager.manager',compact('managers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manager.create_manager');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Aqui se validan los campos antes de guardarlos en la base de datos
        $rules = [
            'management_name' => 'required',
            'manager' => 'required',
            'vacancy' => 'required',
        ];
        
            //Aqui se modifican los mensajes de validacion antes de guardarlos en la base de datos
            $messages = [
                'management_name.required' => 'Agrega el nombre de la Gerencia.',
                'manager.required' => 'Agrega el nombre del Gerente',
                'vacancy.required' =>'Agrega la cantidad de vacantes y si no hay vacantes debes de introducir el valor de 0 para poder guardar.'
            ];
            
            $this->validate($request, $rules, $messages);

            $manager = new Manager;
            $manager->management_name = $request->management_name;
            $manager->manager = $request->manager;
            $manager->vacancy = $request->vacancy;
            $manager->save();

            return redirect()->route('manager.index')
            ->with('success','La Gerencia ha sido creada exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Manager  $manager
     * @return \Illuminate\Http\Response
     */
    public function show(Manager $manager)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Manager  $manager
     * @return \Illuminate\Http\Response
     */
    public function edit(Manager $manager)
    {
        return view('manager.edit_manager',compact('manager'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Manager  $manager
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $manager)
    {
         //Aqui se validan los campos antes de guardarlos en la base de datos
         $rules = [
            'management_name' => 'required',
            'manager' => 'required',
            'vacancy' => 'required',
        ];
        
            //Aqui se modifican los mensajes de validacion antes de guardarlos en la base de datos
            $messages = [
                'management_name.required' => 'Agrega el nombre de la Gerencia.',
                'manager.required' => 'Agrega el nombre del Gerente',
                'vacancy.required' =>'Agrega la cantidad de vacantes y si no hay vacantes debes de introducir el valor de 0 para poder guardar.'
            ];
            
            $this->validate($request, $rules, $messages);

            $manager = Manager::find($manager);
            $manager->management_name = $request->management_name;
            $manager->manager = $request->manager;
            $manager->vacancy = $request->vacancy;
            $manager->save();

            return redirect()->route('manager.index')
            ->with('success','La Gerencia ha sido modificada exitosamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Manager  $manager
     * @return \Illuminate\Http\Response
     */
    public function destroy(Manager $manager)
    {
        $manager->delete();
        return redirect()->route('manager.index')
        ->with('success','La Gerencia ha sido eliminada exitosamente.');
    }
}

resources/views/manager/create_manager.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Crear Gerencia - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
                Crear Gerencia
            </h3>
            <a type="button" class="btn btn-primary float-right" href="{{ route('manager.index') }}"> Regresar</a>
          </div>
        
          <div class="card-body">
           {{-- Formulario Para guardar la Gerencia --}}
           <form action="{{ route('manager.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">   
          <div class="col-6">
            <div class="form-group">
              <label>Nombre Gerente</label>
              <input type="text" class="form-control" id="management_name" name="management_name">
              @error('management_name')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>
          <div class="col-6">
            <div class="form-group">
              <label>Gerencia</label>
              <input type="text" class="form-control" id="manager" name="manager">
              @error('manager')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>
          <div class="col-6">
            <div class="form-group">
              <label>Vacante</label>
              <input type="number" class="form-control" id="vacancy" name="vacancy">      
              @error('vacancy')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>
        
          </div>
          <button  type="submit" class="btn btn-success">Guardar</button>
          </form>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>

@endsection

resources/views/manager/edit_manager.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Editar Gerencia - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
                Editar Gerencia
            </h3>
            <a type="button" class="btn btn-primary float-right" href="{{ route('manager.index') }}"> Regresar</a>
          </div>
        
          <div class="card-body">
           {{-- Formulario Para guardar la Gerencia --}}
           <form action="{{ route('manager.update',$manager->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">   
          <div class="col-6">
            <div class="form-group">
              <label>Nombre Gerente</label>
              <input type="text" class="form-control" value="{{ $manager->management_name }}" id="management_name" name="management_name">
              @error('management_name')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>
          <div class="col-6">
            <div class="form-group">
              <label>Gerencia</label>
              <input type="text" class="form-control" value="{{ $manager->manager }}" id="manager" name="manager">
              @error('manager')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>
          <div class="col-6">
            <div class="form-group">
              <label>Vacante</label>
              <input type="number" class="form-control" value="{{ $manager->vacancy }}" id="vacancy" name="vacancy">      
              @error('vacancy')
              <div class="alert alert-warning alert-dismissible mt-2">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-exclamation-triangle"></i> Alerta!</h5>
                {{ $message }}
              </div>
              @enderror      
            </div>
          </div>
        
          </div>
          <button  type="submit" class="btn btn-success">Guardar</button>
          </form>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>

@endsection

resources/views/manager/manager.blade.php
{{-- Aqui se coloca la plantilla del panel de administrador --}}
@extends('layouts.main')

{{-- Aqui se coloca el titulo de esta pagina que se esta desarroollando --}}
@section('title', 'Gerencias - Administración')

{{-- Aqui la seccion que trae el contenido centrada a la plantilla --}}
@section('section')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">
                Administraci&oacute;n de Gerencias
            </h3>
            <a type="button" class="btn btn-success float-right" href="{{ route('manager.create') }}"><i class="fas fa-plus"></i> Agregar</a>
          </div>
         
          <!-- /.card-header -->
          {{-- Lista de Gerencias --}}
          <div class="card-body">
            @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissible">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <h5><i class="icon fas fa-check"></i> Alerta!</h5>
              <p>{{ $message }}</p>
            </div>
            @endif
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>Nombre Gerente</th>
                <th>Gerencia</th>
                <th>Vacante</th>
                <th>Acciones</th>
              </tr>
              </thead>
              <tbody>
                @foreach ($managers as $manager)
                <tr>
                <td>{{$manager->management_name}}
                </td>
                <td>{{$manager->manager}}
                </td>
                <td>{{$manager->vacancy}}
                </td>
                <td><div class="btn-group">
                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" data-offset="-52" aria-expanded="true">
                      <i class="fas fa-bars"></i>
                    </button>
                    <div class="dropdown-menu" role="menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-52px, 31px, 0px);">
                      <form action="{{ route('manager.destroy',$manager->id) }}" method="Post">
                        <a href="{{ route('manager.edit',$manager->id) }}" class="dropdown-item"> <i class="fas fa-bars"></i> Editar</a>
                        @csrf
                        @method('DELETE')
                        <button  type="submit" class="dropdown-item"> <i class="fas fa-bars"></i> Eliminar</button> 
                      </form>
                     </div>
                  </div></td>
              </tr>
                @endforeach
              </tbody>
              <tfoot>
              <tr>
                <th>Nombre Gerente</th>
                <th>Gerencia</th>
                <th>Vacante</th>
                <th>Acciones</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
@endsection